ARDUINO_VARIANT = generic
SERIAL_PORT = /dev/ttyAMC0
USER_DEFINE = -D_SSID_=\"YourSSID\" -D_WIFI_PASSWORD_=\"YourPassword\"
#ARDUINO_LIB_PATH = /home/jorge/sketchbook/libraries
FLASH_SIZE = 512K
FLASH_FREQ = 40MHz

include ../arduinoEsp8266.mk
